# Site settings
email: b@banjiewen.net
baseurl: ""
url: "http://banjiewen.net" # the base hostname & protocol for your site
twitter_username: banjiewen
github_username:  banjiewen
permalink: /:slug.html

# Build settings
markdown: kramdown
