# Site settings
email: ba@b20n.net
baseurl: ""
url: "http://b20n.net" # the base hostname & protocol for your site
twitter_username: _b20n
github_username:  b20n
permalink: /:slug.html

# Build settings
markdown: kramdown
